# Generated by Django 2.2.1 on 2019-06-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='img',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(choices=[('A +ve', 'A +ve'), ('B +ve', 'B +ve'), ('AB +ve', 'AB +ve'), ('O +ve', 'O +ve'), ('A -ve', 'A -ve'), ('B -ve', 'B -ve'), ('AB -ve', 'AB -ve'), ('O -ve', 'O -ve')], default='A +ve', max_length=7),
        ),
        migrations.AlterField(
            model_name='donor',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
    ]
