# Generated by Django 2.2.1 on 2019-06-18 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20190618_0535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='name_id',
            new_name='user',
        ),
    ]
