# Generated by Django 2.2.1 on 2019-06-16 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20190602_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
